import type { Metadata } from "next";
import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "ພັດທະນາ SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider>
          <main>
            {children}
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
